meta_product_name: "Pawkeo"
meta_title: "Pawkeo - Find a spot!"
meta_description: "Pawkeo helps you find a spot to park your car, around you or a specific address."
meta_image: "imagetagcover.jpg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards